| Year | Title                                                                                                                                                                                      | Link                                                  |
|------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------|
| 2020 | Application of Behavioral Risk Factor Surveillance System Sampling Weights to Transgender Health Measurement.                                                                              | https://www.ncbi.nlm.nih.gov/pubmed/32084102          |
| 2020 | Ask Again: Including Gender Identity in Longitudinal Studies of Aging                                                                                                                      | https://pubmed.ncbi.nlm.nih.gov/32838429/             |
| 2020 | The Use of Methodologies in Littman (2018) Is Consistent with the Use of Methodologies in Other Studies Contributing to the Field of Gender Dysphoria Research: Response to Restar (2019). | https://www.ncbi.nlm.nih.gov/pubmed/31953699          |
| 2020 | Beyond circles and squares: A commentary on updating pedigree nomenclature to better represent patient diversity.                                                                          | https://www.ncbi.nlm.nih.gov/pubmed/32103563          |
| 2020 | Collection of Gender Identity in National Case Notifications of Chlamydia, Gonorrhea, and Primary and Secondary Syphilis, 2018                                                             | https://pubmed.ncbi.nlm.nih.gov/32815904/             |
| 2020 | Survey of Principal Investigators in Biobanking: Knowledge, Attitudes, and Research Behaviors About Transgender and Gender-Diverse Patients                                                | https://pubmed.ncbi.nlm.nih.gov/32525751/             |
| 2020 | Technology-Based Stepped Care to Stem Transgender Adolescent Risk Transmission: Protocol for a Randomized Controlled Trial (TechStep)                                                      | https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7458064/ |
| 2020 | Tracking Trends of Transgender Health Research Online: Are Researchers and the Public on the Same Page?                                                                                    | https://pubmed.ncbi.nlm.nih.gov/32356500/             |
| 2020 | What Sexual and Gender Minority People Want Researchers to Know About Sexual Orientation and Gender Identity Questions: A Qualitative Study                                                | https://pubmed.ncbi.nlm.nih.gov/32875381/             |
| 2019 | Documenting Research with Transgender, Nonbinary, and Other Gender Diverse (Trans) Individuals and Communities: Introducing the Global Trans Research Evidence Map                         | https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6400230/ |
| 2019 | Improving the health of trans people: the need for good data                                                                                                                               | https://pubmed.ncbi.nlm.nih.gov/31376853/             |
| 2019 | Self-Reported Gender Identity and Sexuality in an Online Sample of Cisgender, Transgender, and Gender-Diverse Individuals: An Exploratory Study                                            | https://pubmed.ncbi.nlm.nih.gov/30332297/             |
| 2019 | Sexual and gender minority health research in nursing                                                                                                                                      | https://pubmed.ncbi.nlm.nih.gov/30527514/             |
| 2019 | The Transgender Lens Is Underrepresented and Overlooked in Transgender Health Research to the Detriment of the Population It Seeks to Serve                                                | https://pubmed.ncbi.nlm.nih.gov/30763170/             |
| 2018 | A Call to Action: The Urgent Need for Trans Inclusive Measures in Mental Health Research                                                                                                   | https://pubmed.ncbi.nlm.nih.gov/29923423/             |
| 2018 | Agreement between medical records and self-reports: Implications for transgender health research                                                                                           | https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6438197/ |
| 2018 | Alcohol research with transgender populations: A systematic review and recommendations to strengthen future studies                                                                        | https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5911250/ |
| 2018 | Bibliometric Analysis of Peer-Reviewed Literature in Transgender Health (1900 - 2017)                                                                                                      | https://pubmed.ncbi.nlm.nih.gov/29562909/             |
| 2018 | Engaging Transgender Patients: Using Social Media to Inform Medical Practice and Research in Transgender Health                                                                            | https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6308274/ |
| 2018 | Sex is not gender and why it matters for population health                                                                                                                                 | https://pubmed.ncbi.nlm.nih.gov/29661391/             |
| 2018 | Transgender Health Research Must Serve Transgender People                                                                                                                                  | https://pubmed.ncbi.nlm.nih.gov/29772104/             |
| 2017 | Acceptability and Feasibility of Using a Novel Geospatial Method to Measure Neighborhood Contexts and Mobility Among Transgender Women in New York City                                    | https://pubmed.ncbi.nlm.nih.gov/29082330/             |
| 2017 | Considerations for Culturally Sensitive Research With Transgender Adults: A Qualitative Analysis                                                                                           | https://pubmed.ncbi.nlm.nih.gov/28276930/             |
| 2017 | Documenting Research With Transgender and Gender Diverse People: Protocol for an Evidence Map and Thematic Analysis                                                                        | https://pubmed.ncbi.nlm.nih.gov/28219417/             |
| 2017 | Guidance and Ethical Considerations for Undertaking Transgender Health Research and Institutional Review Boards Adjudicating This Research                                                 | https://pubmed.ncbi.nlm.nih.gov/29098202/             |
| 2017 | More Research Is Needed to Understand the Trans Community                                                                                                                                  | https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5425862/ |
| 2017 | Need for More Research on and Health Interventions for Transgender People                                                                                                                  | https://pubmed.ncbi.nlm.nih.gov/28063463/             |
| 2017 | Research Disparities in Female-to-Male Transgender Genital Reconstruction: The Charge for High-Quality Data on Patient Reported Outcome Measures                                           | https://pubmed.ncbi.nlm.nih.gov/28177977/             |
| 2017 | Review of the Transgender Literature: Where Do We Go From Here?                                                                                                                            | https://pubmed.ncbi.nlm.nih.gov/29082332/             |
| 2017 | The Need of Patient Involvement in Transgender Health Care Research                                                                                                                        | https://pubmed.ncbi.nlm.nih.gov/29198506/             |
| 2017 | Transform Health Arkansas: A Transgender-Led Partnership Engaging Transgender/Non-Binary Arkansans in Defining Health Research Priorities                                                  | https://pubmed.ncbi.nlm.nih.gov/29332856/             |
| 2017 | Transgender Health: New Zealand's Innovative Statistical Standard for Gender Identity                                                                                                      | https://pubmed.ncbi.nlm.nih.gov/27997231/             |
| 2017 | Transgender-inclusive Measures of Sex/Gender for Population Surveys: Mixed-methods Evaluation and Recommendations                                                                          | https://pubmed.ncbi.nlm.nih.gov/28542498/             |
| 2017 | Transgender Research in the 21st Century: A Selective Critical Review From a Neurocognitive Perspective                                                                                    | https://pubmed.ncbi.nlm.nih.gov/29050504/             |
| 2016 | Advancing methods for US transgender health research.                                                                                                                                      | http://www.ncbi.nlm.nih.gov/pubmed/26845331           |
| 2016 | Design Issues in Transgender Studies.                                                                                                                                                      | http://www.ncbi.nlm.nih.gov/pubmed/27429191           |
| 2016 | Perceptions of Barriers to and Facilitators of Participation in Health Research Among Transgender People                                                                                   | https://pubmed.ncbi.nlm.nih.gov/28861532/             |
| 2016 | Prevalence of Transgender Depends on the "Case" Definition: A Systematic Review.                                                                                                           | http://www.ncbi.nlm.nih.gov/pubmed/27045261           |
| 2016 | Priorities for transgender medical and healthcare research.                                                                                                                                | http://www.ncbi.nlm.nih.gov/pubmed/26825469           |
| 2016 | Reporting Sex, Gender, or Both in Clinical Research?                                                                                                                                       | https://pubmed.ncbi.nlm.nih.gov/27802482/             |
| 2016 | Research Priorities for Gender Nonconforming/Transgender Youth: Gender Identity Development and Biopsychosocial Outcomes                                                                   | https://pubmed.ncbi.nlm.nih.gov/26825472/             |
| 2016 | There Is Reason for Optimism: An Introduction to the Special Issue on Research Needs in Transgender Health and Medicine                                                                    | https://pubmed.ncbi.nlm.nih.gov/26910275/             |
| 2015 | Adding value to rare tissue samples donated to biobanks: characterisation of breast tissue and primary cell cultures obtained from a female-to-male transgender patient.                   | http://www.ncbi.nlm.nih.gov/pubmed/24715474           |
| 2015 | Current and Future Direction of Gender Dysphoria and Gender Incongruence Research.                                                                                                         | http://www.ncbi.nlm.nih.gov/pubmed/26696223           |
